version: '3'

services:
    node:
        restart: always
        build: node
        ports:
            - 4200:4200
        volumes:
          - ../../../src/apps/inlook:/app

    php:
        build: php
        ports:
          - 9200:9200
        volumes:
          - ../../../src/services/mailer:/app

    mailhog:
       image: mailhog/mailhog
       ports:
         - 8025:8025