version: '3'

services:

  # --- Infrastructure ---

  postgres:
    image: postgres:10.3 # https://hub.docker.com/_/postgres/
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: JklM8765
    ports:
      - 5432:5432

  postgres-admin:
    image: fenglc/pgadmin4:2.1 # https://hub.docker.com/r/fenglc/pgadmin4/
    restart: always
    volumes:
      - postgres-admin-data:/var/lib/pgadmin
    ports:
      - 5050:5050
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3.7.4-management-alpine # https://hub.docker.com/_/rabbitmq/
    restart: always
    hostname: rabbitmq-host
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

# --- Volumes ---

volumes:
  postgres-data:
  postgres-admin-data:
  rabbitmq-data:
