version: '3'

services:

  # --- Infrastructure ---

  postgres:
    image: postgres:10.3 # https://hub.docker.com/_/postgres/
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: JklM8765
    ports:
      - 5432:5432
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: postgres

  postgres-admin:
    image: fenglc/pgadmin4:2.1 # https://hub.docker.com/r/fenglc/pgadmin4/
    restart: always
    volumes:
      - postgres-admin-data:/var/lib/pgadmin
    ports:
      - 5050:5050
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3.7.4-management-alpine # https://hub.docker.com/_/rabbitmq/
    restart: always
    hostname: rabbitmq-host
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: rabbitmq

  mongo:
    image: mongo:3
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: mongo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: elasticsearch

  graylog:
    image: eposgmbh/graylog:latest
    build: ./graylog
    volumes:
      - graylog-data:/usr/share/graylog/data/journal
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    links:
      - mongo
      - elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000 # Graylog web interface and REST API
      - 514:514 # Syslog TCP
      - 514:514/udp # Syslog UDP
      - 12201:12201 # GELF TCP
      - 12201:12201/udp # GELF UDP

# --- Volumes ---

volumes:
  postgres-data:
  postgres-admin-data:
  rabbitmq-data:
  mongo-data:
  elasticsearch-data:
  graylog-data:
